- blocks/article-hero/article-hero.css
- blocks/article-hero/article-hero.js
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/transform-your-space-and-empower-your-life
- After: https://hero-collection--24life--hlxsites.hlx.page/transform-your-space-and-empower-your-life
> Article Hero: Add link to collection and author

- scripts/scripts.js
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/rebalance-and-strengthen-with-these-three-yoga-moves-from-tiffany-cruikshank#extended-side-angle-to-revolved-lunge
- After: https://fix-youtube--24life--hlxsites.hlx.page/rebalance-and-strengthen-with-these-three-yoga-moves-from-tiffany-cruikshank#extended-side-angle-to-revolved-lunge
> Fix youtube link

- blocks/article-author/article-author.js
- blocks/article-list/article-list.css
- blocks/article-list/article-list.js
- blocks/card/card.css
- blocks/card/card.js
- helix-query.yaml
- scripts/ffetch.js
- templates/article/article.js
- templates/author/author.css
Fix #14 
Test URLs:
- After: https://14-author-profile--24life--hlxsites.hlx.page/author/24life
- - After: https://14-author-profile--24life--hlxsites.hlx.page/author/trish-shallest
> Feat #14: create author page with cards

- tools/sidekick/config.json
- tools/sidekick/library.html
Branch: 32-Setup-Block-Library
Fix #32
Test URLs:
- After: https://32-setup-block-library--24life--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks
> #32 setup block library

- blocks/article-hero/article-hero.js
- templates/article/article.js
- tools/sidekick/plugins/authors/authors.js
Made it possible to show in Block library. 
Test URLs:
- https://article-hero-block--24life--hlxsites.hlx.page/isabel-beats-incredible-odds
- https://article-hero-block--24life--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/block-library/blocks/article-hero&index=0
> Article hero block

- helix-query.yaml
Add the block-library to the exclude list.
Test URLs:
- After: https://update-indexer-exclude--24life--hlxsites.hlx.page/
> added block-library to exclude list

- blocks/article-author/article-author.css
- blocks/article-author/article-author.js
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/should-you-try-algal-proteins-the-101-on-chlorella-and-spirulina
- After: https://author-social--24life--hlxsites.hlx.page/fuel/2020/should-you-try-algal-proteins-the-101-on-chlorella-and-spirulina
> add social links to author block on article

- blocks/article-hero/article-hero.css
- blocks/article-hero/article-hero.js
- css updates to match target site
Fix #<gh-issue-id>
Test URLs:
- After:  https://11-article-hero-block--24life--hlxsites.hlx.page/isabel-beats-incredible-odds
> Fix #11 article-hero block: css updates to match reference site

- blocks/magazine-list/magazine-list.css
- blocks/magazine-list/magazine-list.js
- blocks/quote/quote.css
- blocks/quote/quote.js
- helix-query.yaml
Fix #4 
Fix #7
Test URLs:
- Before: https://main--24life--hlxsites.hlx.live/magazine
- After: https://magazine-list--24life--hlxsites.hlx.live/magazine
> Magazine List

- blocks/article-author/article-author.js
- helix-query.yaml
- templates/article/article.js
Fix #39 
Click on the social links for the article. It should open a new window to share the article.
Click on the author's social links at the bottom of the page. It should open a new tab to the author's social page.
Test URLs:
- Before: https://main--24life--hlxsites.hlx.live/focus/2017/one-word-is-the-key-to-your-strategy
- After: https://social-window--24life--hlxsites.hlx.live/focus/2017/one-word-is-the-key-to-your-strategy
> Social links new window

- blocks/article-slides/article-slides.css
- blocks/article-slides/article-slides.js
Fix #55
Test URLs:
- After: https://55-home-carousel--24life--hlxsites.hlx.page/block-library/blocks/article-slides
- - After: https://55-home-carousel--24life--hlxsites.hlx.page/
> Feat #55: article carousel on home page

- scripts/scripts.js
- styles/lazy-styles.css
Fix #87
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/recover/2020/your-yoga-playlist
- After: https://spotify--24life--hlxsites.hlx.page/recover/2020/your-yoga-playlist
> Feat #87 Spotify Embed

- blocks/columns/columns.css
- blocks/columns/columns.js
Rendering in blocks library fixed
Code is flexible now 
Fix #80 
Test URLs:
- After:  https://80-collections-landing-page--24life--hlxsites.hlx.page/collections
> 80 collections landing page

- scripts/scripts.js
Autoblocking is evil, let's not use it. Templates makes more sense in specific use cases.  
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/block-library/blocks/columns
- After: https://disable-autoblocking--24life--hlxsites.hlx.page/block-library/blocks/columns
> Disable Hero autoblocking

- blocks/columns/columns.js
- scripts/scripts.js
this code is so ugly, copied from volvo. 
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/drafts/wingeier/snack-attack
- After: https://autolink-images--24life--hlxsites.hlx.page/drafts/wingeier/snack-attack
> autolink pictures

- blocks/quote/quote.js
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/block-library/blocks/quote
- After: https://quote-optional--24life--hlxsites.hlx.page/block-library/blocks/quote
> Quote: make author value optional

- blocks/article-hero-video/article-hero-video.js
- scripts/scripts.js
- After: https://video-authors--24life--hlxsites.hlx.page/template-magazine-article
- Library: https://video-authors--24life--hlxsites.hlx.page/block-library/blocks/article-hero-video
> article-hero-video: don't auto-decorate videos if not in block. get authors from metadata.

- blocks/article-list/article-list.js
- blocks/card/card.js
index is already updated
Fix #93
- After: https://93-authors--24life--hlxsites.hlx.page/author/mark-smith
> Handle multiple authors per article #93

- blocks/card/card.css
- blocks/card/card.js
Fix #36 
Test URLs:
- Before: https://main--24life--hlxsites.hlx.live/magazine/volume-5-issue-12
- After: https://card-large-right--24life--hlxsites.hlx.live/magazine/volume-5-issue-12
> update card max-width and right card layout

- helix-query.yaml
we already have magazines.json for the list of issuess
> Remove - /magazine/** from articles.json

- blocks/article-hero-video/article-hero-video.css
- blocks/article-hero-video/article-hero-video.js
mp4 support for article hero video 
Fix #31 
Example from Block library:  https://31-magazine-article-hero-block-with-video--24life--hlxsites.hlx.page/tools/sidekick/library.html?plugin=blocks&path=/block-library/blocks/article-hero-video&index=1
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/drafts/ashrigondeka/the-change-master-john-berardis-second-act-will-help-you-too
- After:  https://31-support-mp4-video-article-hero-block--24life--hlxsites.hlx.page/drafts/ashrigondeka/the-change-master-john-berardis-second-act-will-help-you-too
- https://31-support-mp4-video-article-hero-block--24life--hlxsites.hlx.page/drafts/ashrigondeka/graphic-designer-by-day-this-gx24-instructor-says-power-jumping-with-you-is-worth-it
- https://31-support-mp4-video-article-hero-block--24life--hlxs …
> #31 mp4 support  added to  article-hero-block 

- .gitignore
- blocks/article-carousel/article-carousel.js
- blocks/article-hero-video/article-hero-video.css
- blocks/article-hero-video/article-hero-video.js
- blocks/article-list/article-list.js
- blocks/article-slides/article-slides.js
- blocks/card/card.css
- blocks/card/card.js
- blocks/columns/columns.css
- helix-query.yaml
- scripts/scripts.js
- styles/lazy-styles.css
- styles/styles.css
- tools/importer/import_article.js
- tools/validation/24life-download-hlx.mjs
- tools/validation/24life-find-invalid-docs.mjs
Fix #<gh-issue-id>
Test URLs:
- After: https://<branch>--24life--hlxsites.hlx.page/
> update feature branch

- blocks/magazine-footer/magazine-footer.css
- blocks/magazine-footer/magazine-footer.js
- blocks/magazine-hero/magazine-hero.js
- scripts/scripts.js
Fix #19
Test URLs:
- Before: https://main--24life--hlxsites.hlx.live/magazine/volume-5-issue-12
- After: https://mag-footer--24life--hlxsites.hlx.live/magazine/volume-5-issue-12
> mag footer block

- blocks/video/video.css
- blocks/video/video.js
- icons/play-btn.svg
Fix #95
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/fitness/2019/hands-up-if-you-want-to-get-more-from-your-high-knee-running
- After:  
-  https://95-video-block--24life--hlxsites.hlx.page/fitness/2019/hands-up-if-you-want-to-get-more-from-your-high-knee-running
- https://95-video-block--24life--hlxsites.hlx.page/focus/2020/movement-helps-people-come-together
> Issue #95 video block with play button

- blocks/collections-explorer/collections-explorer.css
- blocks/collections-explorer/collections-explorer.js
List collections w/full-width background image 
Fix #112 
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page
- After: https://112-collections-block--24life--hlxsites.hlx.page
> Issue #112 |  Collections Explorer

- blocks/article-list/article-list.js
- fstab.yaml
Fix #37 
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/category/lifestyle
- After: https://issue37-foldermapping-v1--24life--hlxsites.hlx.page/category/lifestyle
> Issue37 foldermapping v1

- blocks/article-list/article-list.js
- blocks/author-list/author-list.css
- blocks/author-list/author-list.js
Fix #124 
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/experts
- After: https://issue122-v1-betterlhs--24life--hlxsites.hlx.live/drafts/meejain/experts
> Issue122 v1 betterlhs

- blocks/article-slides/article-slides.css
- blocks/header/header.css
- blocks/header/header.js
- icons/hamburger.svg
This lazy loads the carousels for each section into the subnav.
It also sets up the search input field.
It includes event listeners for the nav and subnav.
Updated menu to use SVGs.
Fix #2
Test URLs:
- After: https://subnav--24life--hlxsites.hlx.live/
> Rebuild of Navigation and Subnav display

- helix-query.yaml
Fix #128 
Test URLs:
- After: https://issue128-updating-queryindex--24life--hlxsites.hlx.page/query-index.json
> Updating the helix-query.yaml file to include 2 more columns

- helix-query.yaml
Fix #135 
Test URLs:
- After: https://issue135-content-helixquery--24life--hlxsites.hlx.page/
> Adding the content to query index metadata

- blocks/article-slides/article-slides.css
- styles/styles.css
Test URLs:
- After: https://home-contrast--24life--hlxsites.hlx.page/
> Fix contrast in home slider

- blocks/footer/footer.css
- scripts/scripts.js
- styles/styles.css
- templates/article/article.css
- tools/importer/import_article.js
I updated a handful of articles where floats is better. 
Fix #142 
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/fitness/2018/a-personal-trainer-on-getting-race-day-ready-and-total-body-cardio-moves
- After: https://142-float--24life--hlxsites.hlx.page/fitness/2018/a-personal-trainer-on-getting-race-day-ready-and-total-body-cardio-moves
- https://142-float--24life--hlxsites.hlx.page/focus/2016/pack-your-bag
- https://142-float--24life--hlxsites.hlx.page/focus/2017/four-reasons-to-meet-up-to-meditate
- https://142-float--24life--hlxsites.hlx.page/focus/2020/wake-up-work-out-get-well-best-of-ces-2020
Library:
- After: https://142-float--24life--hlxsites.hlx.page/block-library/blocks/float-images
> #142 float images

- blocks/magazine-hero/magazine-hero.js
- head.html
- styles/styles.css
- tools/importer/import_article.js
Fix #162
scroll to article: 
https://162-magazine-explore-button--24life--hlxsites.hlx.page/magazine/volume-3-issue-3
video as section's next sibling: https://162-magazine-explore-button--24life--hlxsites.hlx.page/magazine/volume-5-issue-2
> #162 Magazine-Issue: Fixed scroll action on explore-this-issue button click

- blocks/article-list/article-list.js
- After: https://simplify-articlelist--24life--hlxsites.hlx.page/author/24life
> article-list.js: simplify using iterator

- blocks/header/header.css
- blocks/search-results/search-results.css
- blocks/search-results/search-results.js
- scripts/lib-franklin.js
Fix #152 #149 
Test URLs:
- Before: https://main--24life--hlxsites.hlx.live/search?q=francisco
- After: https://issue152-css-layout--24life--hlxsites.hlx.live/search?q=francisco
> #152 fixing CSS Layout cumulative shift for search results

- blocks/article-hero-video/article-hero-video.css
- blocks/article-hero-video/article-hero-video.js
Fix #156 
Test URLs:
- After: https://156-magazine-hero-show-section-subheader--24life--hlxsites.hlx.page/focus/2018/create-a-community-you-love
> #156 Magazine Hero: section linked

- blocks/header/header.css
- styles/styles.css
Fix #169 
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/magazine/volume-6-issue-1
- After: https://issue169-layoutshift-magazine--24life--hlxsites.hlx.page/magazine/volume-6-issue-1
> #169 - Removing the default mandate of keeping a header size = var(--nav-height)

- blocks/article-slides/article-slides.css
- blocks/magazine-hero/magazine-hero.css
- Font changed to 23px for less than 600px width screens
Fix #151 
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/magazine/volume-4-issue-11
- After: https://151-magaine-hero-on-mobile-text-cut-off--24life--hlxsites.hlx.page/magazine/volume-4-issue-11
<details>
<summary>Tested on Mobile</summary>
</details>
> #151 Adjusted Magazine hero H1 tag size for Mobile 

- blocks/header/header.js
- blocks/search-results/search-results.js
- After: https://search--24life--hlxsites.hlx.page/search?s=hiit+programs
compared with https://www.24life.com/?s=hiit+programs
> Use s= for search query to be closer to the reference

- blocks/article-author/article-author.js
Fix #157
done: fix articles in https://main--24life--hlxsites.hlx.page/author/elle-penner 
Test URLs:
- After: https://157-author-comma--24life--hlxsites.hlx.page/fuel/2017/salad-sparkle
> article-author: allow partial match to display author

- blocks/header/header.css
- blocks/header/header.js
Set a default style on nav-fragments.
Updated the change listener.
Fix #181 
Test URLs:
- After: https://nav-resize-fix--24life--hlxsites.hlx.page/
> Window Resize Navigation Bug

- blocks/magazine-hero/magazine-hero.js
Fix #170 
Test URLs:
- After: 
- https://170-magazine-hero-invert-text-color--24life--hlxsites.hlx.page/magazine/volume-5-issue-1
- https://170-magazine-hero-invert-text-color--24life--hlxsites.hlx.page/magazine/volume-4-issue-1
> #170 Magazine: Titlecolor property used for inverting text color

- blocks/columns/columns.css
- blocks/columns/columns.js
- tools/importer/import_older_magazines.js
Fix #179
Test URLs:
- After:  
- https://179-import-older-magazines--24life--hlxsites.hlx.page/drafts/ashrigondeka/old-magazines/volume-1-issue-2
- https://179-import-older-magazines--24life--hlxsites.hlx.page/drafts/ashrigondeka/old-magazines/volume-1-issue-1
- https://179-import-older-magazines--24life--hlxsites.hlx.page/drafts/ashrigondeka/old-magazines/volume-1-issue-4
- https://179-import-older-magazines--24life--hlxsites.hlx.page/drafts/ashrigondeka/old-magazines/volume-2-issue-2
- https://179-import-older-magazines--24life--hlxsites.hlx.page/drafts/ashrigondeka/old-magazines/volume-1-issue-3
- https://179-import-older-magazines--24life--hlxsites.hlx.page/drafts/ashrigondeka/old-magazines/volume-2-issue-1
- …
> Issue #179 Import Older magazine issues

- blocks/article-hero-video/article-hero-video.css
Test URLs:
- Before: https://main--24life--hlxsites.hlx.live/block-library/blocks/article-hero-video
- After: https://hero-relative--24life--hlxsites.hlx.live/block-library/blocks/article-hero-video
> Properly scope the absolute position

- blocks/article-slides/article-slides.css
- blocks/article-slides/article-slides.js
Test URLs:
- After: https://article-slides-manual--24life--hlxsites.hlx.page/
> Article slides: support static content to improve LHS

- blocks/card/card.css
- blocks/card/card.js
- blocks/section-hero/section-hero.css
https://dequeuniversity.com/rules/axe/4.7/heading-order
Test URLs:
- After: https://card-noheading--24life--hlxsites.hlx.page/
- After: https://card-noheading--24life--hlxsites.hlx.page/focus
> Card: accessibility - Heading elements are not in a sequentially-descending order

- tools/importer/import_magazine.js
- tools/importer/import_older_magazines.js
Added page description.
Changed the Magazine Footer block to Magazine Summary.
Commented out the Subscribe Form since it's deferred.
Removed HTML tags from link text.
Fix #191 - Remove HTML tag from link text
Fix #192 - Summary
Fix #194 - Missing description
> Import magazine updates

- blocks/magazine-list/magazine-list.css
- blocks/magazine-list/magazine-list.js
Test URLs:
- Before: https://main--24life--hlxsites.hlx.live/magazine
- After: https://magazine-cleanup--24life--hlxsites.hlx.live/magazine
> Improve LHS for Magazine index

- blocks/card/card.js
- blocks/columns/columns.js
- blocks/magazine-summary/magazine-summary.js
- tools/validation/rewrite-links.mjs
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/magazine/volume-4-issue-8
- After: https://summary-path--24life--hlxsites.hlx.page/magazine/volume-4-issue-8
- https://summary-path--24life--hlxsites.hlx.page/magazine/volume-4-issue-7
> Improve detection of links in magazine-summary and detect section of any card

- blocks/article-hero-video/article-hero-video.js
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/inert
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/focus/2020/graphic-designer-by-day-this-gx24-instructor-says-power-jumping-with-you-is-worth-it
- After: https://inert--24life--hlxsites.hlx.page/focus/2020/graphic-designer-by-day-this-gx24-instructor-says-power-jumping-with-you-is-worth-it
> Make video non-interactive, not even by keyboard

- blocks/article-hero-video/article-hero-video.css
- blocks/article-hero-video/article-hero-video.js
- blocks/magazine-summary/magazine-summary.js
- scripts/lib-franklin.js
- styles/styles.css
- templates/article/article.js
- tools/importer/import_magazine.js
- tools/importer/import_older_magazines.js
Fix #202
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/focus/2019/the-change-master-john-berardis-second-act-will-help-you-too
- After: https://202-magazine-article--24life--hlxsites.hlx.page/focus/2019/the-change-master-john-berardis-second-act-will-help-you-too
> fix: #202 magazine article LHS

- blocks/section-hero/section-hero.css
- blocks/section-hero/section-hero.js
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/fitness
- After: https://section-colors--24life--hlxsites.hlx.page/fitness
> Increase contrast for /focus and /fitness

- 24life/scripts/delayed.js
Fix #46
Test URLs:
- After: https://46-integrate-analytics--24life--hlxsites.hlx.page/
> issue #46 Integrate adobe analytics

- 24life/blocks/article-author/article-author.js
- 24life/blocks/article-hero-video/article-hero-video.js
- 24life/blocks/article-hero/article-hero.js
- 24life/blocks/card/card.js
- 24life/blocks/header/header.js
- 24life/blocks/magazine-summary/magazine-summary.js
- 24life/blocks/section-hero/section-hero.js
Test URLs:
- After: https://24lifepath--24life--hlxsites.hlx.page/
> Fix links with wrong prefix

- helix-sitemap.yaml
Fix #26 
Test URLs:
- After: https://issue26-sitemap--24life--hlxsites.hlx.page/
> #26 - Updating helix-sitemap.yaml for the subpage - https://www.24hourfitness.com/24life/

- 24life/blocks/search-results/search-results.js
Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/24life/search?s=fight
- After: https://search2--24life--hlxsites.hlx.page/24life/search?s=fight
> Fetch all pages for search

- 24life/blocks/newsletter-form/newsletter-form.css
Fix #216 
Test URLs:
- Before: https://main--24life--hlxsites.hlx.live/24life/newletter-full
- After: https://issue216-cache-purge-test--24life--hlxsites.hlx.live/24life/newsletter-full
> issue216 - Cache purge test

- 24life/blocks/newsletter-form/newsletter-form.css
> Revert "issue216 - Cache purge test"

- 24life/scripts/scripts.js
const LCP_BLOCKS = ['section-hero', 'article-slides']; // add your LCP blocks to the list
Fix #213
Test URLs:
- Before: https://main--24life--hlxsites.hlx.live/
- After: https://lcp-block--24life--hlxsites.hlx.live/
> Add article-slides to LCP

- head.html
Fix #224 
Test URLs:
- Before: https://main--24life--hlxsites.hlx.live/24life
- After: https://issue224-flickering-issue--24life--hlxsites.hlx.live/24life
> Eliminate flicker introduced by Adobe Target - Happening on https://www.24hourfitness.com/24life/
